globals:
  seed: 5713
  debug: True
  mixup: False
  device: cpu
  dir_train: '../../data_ignore/input/train/'
  dir_test: '../../data_ignore/input/test/'
  path_train_tp: '../../data_ignore/input/train_tp.csv'
  path_sample_submission: '../../data_ignore/input/sample_submission.csv'
  dir_save: '../../data/exp/'
  dir_save_ignore: '../../data_ignore/exp/'

dataset:
  name: SpectrogramDataset
  params:
    period: 5
    shift_duration: 4
    img_size: 224
  melspec_params:
    n_mels: 128
    # n_mels: 256
    # fmin: 20
    # fmax: 16000

loader:
  train:
    batch_size: 20
    # batch_size: 1
    shuffle: True
    num_workers: 2
    # num_workers: 1
  valid:
    batch_size: 10
    shuffle: False
    num_workers: 2

split:
  seed: 5713
  n_fold: 5
 
loss:
  name: ResNetLoss
  params:
    loss_type: bce

model:
  name: ResNet18
  params:
    pretrained: True
    n_classes: 24

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10
