globals:
  seed: 5713
  debug: True
  dir_train: '../../data_ignore/input/train/'
  dir_test: '../../data_ignore/input/test/'
  path_train_tp: '../../data_ignore/input/train_tp.csv'
  path_sample_submission: '../../data_ignore/input/sample_submission.csv'
  dir_save: '../../data/exp/'
  dir_save_ignore: '../../data_ignore/exp/'

dataset:
  name: 'SpectrogramDataset'
  params:
    period: 5
    shift_duration: 4
    img_size: 224
  melspec_params:
    n_mels: 128
    # fmin: 20
    # fmax: 16000

loader:
  train:
    batch_size: 20
    shuffle: True
    num_workers: 2
  valid:
    batch_size: 10
    shuffle: False
    num_workers: 2

split:
  seed: 5713
  n_fold: 5
